version: '3'
volumes:
  geo-db-data:
  nifi-database-repository:
  nifi-flowfile-repository:
  nifi-content-repository:
  nifi-provenance-repository:
  nifi-state:
  nifi-logs:
  nifi-nars:
  nifi-conf:

services:
  dba:
    image: dpage/pgadmin4:latest
    container_name: ldes-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ldes@ldes.be
      PGADMIN_DEFAULT_PASSWORD: ldes
    ports:
      - 8001:80
    depends_on:
      - postgis
  
  geoserver:
    build: docker/geoserver
    container_name: ldes-postgis-geoserver
    ports:
      - 8002:8080
    environment:
      - GEOSERVER_ADMIN_PASSWORD=ldes
      - GEOSERVER_ADMIN_USER=ldes
      - POSTGRES_JNDI=TRUE
      - HOST=postgis
      - POSTGRES_DB=mobility_hindrance
      - POSTGRES_USER=ldes
      - POSTGRES_PASS=ldes
    depends_on:
      - postgis

  postgis:
    build: ./docker/postgress
    container_name: ldes-postgis
    environment:
      POSTGRES_DB: mobility_hindrance
      POSTGRES_USER: ldes
      POSTGRES_PASSWORD: ldes
    volumes:
        - geo-db-data:/var/lib/postgresql
    ports:
      - 5432:5432
  gdal:
    build: docker/gdal
    container_name: ldes-gdal
    image: digitaalvlaanderen/gdal
    ports:
      - 8090:8090
  nifi:
    build: docker/nifi
    container_name: ldes-nifi
    restart: unless-stopped
    ports:
      # HTTPS
      - 8443:8443/tcp

    environment:
      - NIFI_UI_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=admin123456789
      - NIFI_WORKFLOW_LISTEN_PORT=9005
      - NIFI_JVM_HEAP_INIT=8g
      - NIFI_JVM_HEAP_MAX=8g
      - POSTGRES_DB=mobility_hindrance
      - POSTGRES_USER=ldes
      - POSTGRES_PASSWORD=ldes
      - POSTGRES_HOST=postgis

